/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import util.Validador;
import dao.MaterialDAO;

/**
 * Diálogo modal para editar los datos de un material ya existente en el inventario.
 * Permite modificar la cantidad, el estado y las observaciones del material indicado,
 * delegando la actualización en {@link dao.MaterialDAO#actualizarMaterial}.
 *
 * @author Equipo1
 * @version 1.0
 */
public class EditarMaterialDialog extends javax.swing.JDialog {

    /**
     * Creates new form EditarMaterialDialog
     */
    public EditarMaterialDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        lblError = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(24, 95, 165));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 45));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/edit.png"))); // NOI18N
        jLabel1.setText("Editar material");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 12, 250, 20));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(28, 32, 40));
        jPanel2.setForeground(new java.awt.Color(210, 70, 70));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(140, 150, 168));
        jLabel2.setText("Material");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 200, 16));

        txtNombre.setBackground(new java.awt.Color(44, 50, 62));
        txtNombre.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(220, 225, 235));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, 410, 32));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(140, 150, 168));
        jLabel3.setText("Estado");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 190, 16));

        cmbEstado.setBackground(new java.awt.Color(44, 50, 62));
        cmbEstado.setForeground(new java.awt.Color(220, 225, 235));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Operativo", "Averiado", "En reparacion", "Obsoleto" }));
        jPanel2.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 98, 195, 32));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(140, 150, 168));
        jLabel4.setText("Cantidad");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 78, 190, 16));

        txtCantidad.setBackground(new java.awt.Color(44, 50, 62));
        txtCantidad.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(220, 225, 235));
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 98, 195, 32));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(140, 150, 168));
        jLabel5.setText("Observaciones");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 142, 200, 16));

        txtObservaciones.setBackground(new java.awt.Color(44, 50, 62));
        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtObservaciones.setForeground(new java.awt.Color(220, 225, 235));
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 410, 60));
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 232, 410, 16));

        btnGuardar.setBackground(new java.awt.Color(24, 95, 165));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorderPainted(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 100, 32));

        btnCerrar.setBackground(new java.awt.Color(44, 50, 62));
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cancelar");
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFocusPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 100, 32));

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
 * Valida los campos del formulario y, si son correctos, actualiza el material
 * en la base de datos mediante {@link dao.MaterialDAO#actualizarMaterial}.
 * Muestra un mensaje de error en {@code lblError} si la validación falla
 * o si no se puede completar la actualización.
 *
 * @param evt Evento de acción del botón Guardar.
 */
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        
        String nombre = txtNombre.getText().trim();
        String estadoNombre = cmbEstado.getSelectedItem().toString();
        int cantidad = Integer.parseInt(txtCantidad.getText());
        String observaciones = txtObservaciones.getText().trim();
        int estado;
        
        if (!Validador.leerMaterial(nombre)) {
            
            lblError.setText("Nombre inválido (mínimo 3 caracteres).");
            
            return;
        }

        try {
            cantidad = Integer.parseInt(txtCantidad.getText().trim());
            
        } catch (NumberFormatException e) {
            lblError.setText("La cantidad debe ser un número entero.");
            
            return;
        }
        if (!Validador.leerCantidad(cantidad)) {
            lblError.setText("Cantidad inválida (debe estar entre 1 y 10 000).");
            
            return;
        }
        
        switch (estadoNombre){
            case "Operativo" ->{
                    estado = 1;
                }
            case "Averiado" ->{
                    estado = 2;
                }
            case "En reparacion" ->{
                    estado = 3;
                }
            default ->{
                    estado = 4;
                }
        }
        
        boolean modificado = MaterialDAO.actualizarMaterial(cantidad, estado, observaciones, nombre);
        
        if(!modificado){
            lblError.setText("No se ha podido modificar, compruebe los campos");
        }
        
        dispose();
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed
    /**
 * Cierra el diálogo sin guardar ningún cambio.
 *
 * @param evt Evento de acción del botón Cancelar.
 */
    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarMaterialDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarMaterialDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarMaterialDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarMaterialDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarMaterialDialog dialog = new EditarMaterialDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
