/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.ProfesorFrame;
import view.AdminPanelFrame;
import dao.UsuarioDAO;
import model.Roles;
import model.Usuario;
import org.mindrot.jbcrypt.BCrypt;
import ssh.TunelSSH;
/**
 * Ventana de inicio de sesión de la aplicación.
 * Permite autenticarse con nombre de usuario y contraseña.
 * Tras una autenticación correcta redirige al panel de administrador
 * ({@link AdminPanelFrame}) o al panel de profesor ({@link ProfesorFrame})
 * según el rol del usuario.
 * Al arrancar abre el túnel SSH necesario para la conexión remota a la BD.
 *
 * @author Equipo1
 * @version 1.0
 */
public class LoginFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCreeden = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblContrasena = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblIconUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblProfe = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.red);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(24, 95, 165));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Gestión del Taller");
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 250, 22));

        lblSubtitulo.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblSubtitulo.setForeground(new java.awt.Color(181, 212, 244));
        lblSubtitulo.setText("IES Miguel Herrero Pereda");
        jPanel1.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 46, 280, 18));

        jPanel3.setBackground(new java.awt.Color(58, 119, 178));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/llave.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 90));

        jPanel2.setBackground(new java.awt.Color(48, 48, 46));
        jPanel2.setPreferredSize(new java.awt.Dimension(460, 530));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreeden.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblCreeden.setForeground(new java.awt.Color(255, 255, 255));
        lblCreeden.setText("Introduce tus creedenciales para acceder");
        jPanel2.add(lblCreeden, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 300, 18));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");
        jPanel2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, 100, 30));

        txtNombre.setBackground(new java.awt.Color(38, 38, 36));
        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(91, 90, 86)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, 380, 34));

        lblContrasena.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        lblContrasena.setText("Contraseña");
        jPanel2.add(lblContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 30));

        txtContrasena.setBackground(new java.awt.Color(38, 38, 36));
        txtContrasena.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(255, 255, 255));
        txtContrasena.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(91, 90, 86)));
        txtContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContrasenaActionPerformed(evt);
            }
        });
        jPanel2.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 380, 34));

        lblError.setForeground(new java.awt.Color(180, 50, 50));
        jPanel2.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 168, 380, 30));

        btnEntrar.setBackground(new java.awt.Color(24, 95, 165));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/login.png"))); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntrar.setBorderPainted(false);
        btnEntrar.setFocusPainted(false);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 380, 36));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 255, 390, 10));

        lblIconUser.setBackground(new java.awt.Color(255, 255, 255));
        lblIconUser.setForeground(new java.awt.Color(255, 255, 255));
        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/user.png"))); // NOI18N
        jPanel2.add(lblIconUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/padlock.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 50));

        jPanel4.setBackground(new java.awt.Color(38, 38, 36));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 41, 39)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAdmin.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(24, 95, 165));
        lblAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/security.png"))); // NOI18N
        lblAdmin.setText("Administrador");
        lblAdmin.setToolTipText("Acceso completo");
        jPanel4.add(lblAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 16));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 130, 40));

        jPanel5.setBackground(new java.awt.Color(38, 38, 36));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 41, 39)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfe.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblProfe.setForeground(new java.awt.Color(15, 110, 86));
        lblProfe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/graduate.png"))); // NOI18N
        lblProfe.setText("Profesor");
        lblProfe.setToolTipText("Solo consulta");
        lblProfe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.add(lblProfe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 16));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 460, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
 * Manejador del campo nombre al pulsar Enter. Sin implementación adicional.
 *
 * @param evt Evento de acción del campo de texto.
 */
    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed
    /**
 * Valida que los campos no estén vacíos, autentica al usuario mediante
 * {@link dao.UsuarioDAO#login} y, si las credenciales son correctas,
 * abre el panel correspondiente al rol (ADMINISTRADOR o PROFESOR).
 * Muestra un mensaje de error en {@code lblError} si la autenticación falla.
 *
 * @param evt Evento de acción del botón Entrar.
 */
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        
        String nombre = txtNombre.getText();
        
        char[] caracteresContrasena = txtContrasena.getPassword();
        
        String contrasena = new String(caracteresContrasena);
        
        if(nombre.isEmpty() || contrasena.isEmpty()){
            lblError.setText("Error: caracteres vacios");
            return;
        }
        
        Usuario usuario = UsuarioDAO.login(nombre, contrasena);
        
        if(usuario == null){
            lblError.setText("Error: usuario y contraseña no coincide");
            
        }
        
        if (usuario != null) {
            dispose();
            if (usuario.getRol() == Roles.ADMINISTRADOR) {
                new AdminPanelFrame(nombre).setVisible(true);
            } else {
                new ProfesorFrame(nombre).setVisible(true);
            }
        }
        
        
    }//GEN-LAST:event_btnEntrarActionPerformed
    /**
 * Simula la pulsación del botón Entrar al pulsar Enter en el campo de contraseña,
 * permitiendo iniciar sesión sin usar el ratón.
 *
 * @param evt Evento de acción del campo de contraseña.
 */
    private void txtContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContrasenaActionPerformed
        btnEntrar.doClick();
    }//GEN-LAST:event_txtContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
            // 1️⃣ Abrir túnel SSH primero
        TunelSSH tunel = new TunelSSH();
        try {
            tunel.abrirTunel();
        } catch (Exception e) {
            System.err.println("Error al abrir tunel SSH: " + e.getMessage());
            return;
        }

        /* Set the Nimbus look and feel */
        // Look and feel setting code (optional) — déjalo igual que lo tienes

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });

        // 3️⃣ Cerrar túnel al cerrar la app
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            tunel.cerrarTunel();
        }));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblContrasena;
    private javax.swing.JLabel lblCreeden;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblProfe;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
