/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.AccesoBaseDatos;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.GestorCSV;

/**
 *
 * @author Equipo1
 */
public class ProfesorFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfesorFrame
     */
    public ProfesorFrame(String nombre) {
        initComponents();
        setLocationRelativeTo(this);
        txtProfesorNombre.setText(nombre);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtProfesorNombre = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnLocalizar = new javax.swing.JButton();
        btnListado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        lblError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 675));

        jPanel1.setBackground(new java.awt.Color(15, 110, 86));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/llavenBlanca.png"))); // NOI18N
        jLabel1.setText("Gestión del Taller - IES Miguel Herrero Pereda");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(159, 225, 203));
        jLabel2.setText("Profesor:");
        jPanel2.add(jLabel2);

        txtProfesorNombre.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel2.add(txtProfesorNombre);

        btnCerrarSesion.setBackground(new java.awt.Color(8, 55, 43));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/login.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(28, 32, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(44, 50, 62));
        txtBuscar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(140, 150, 168));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 32));

        cmbEstado.setBackground(new java.awt.Color(44, 50, 62));
        cmbEstado.setForeground(new java.awt.Color(220, 225, 235));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los estados", "Operativo", "Averiado", "En reparacion", "Obsoleto" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        jPanel3.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 32));

        cmbCategoria.setBackground(new java.awt.Color(44, 50, 62));
        cmbCategoria.setForeground(new java.awt.Color(220, 225, 235));
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las categorias", "PC’s para prácticas", "Componentes hardware", "Equipos de red", "Cableado estructurado", "Herramientas de soldadura y generales", "Material fungible" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        jPanel3.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 180, 32));

        btnLocalizar.setBackground(new java.awt.Color(15, 110, 86));
        btnLocalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/location.png"))); // NOI18N
        btnLocalizar.setText("Localizar en la web");
        btnLocalizar.setBorderPainted(false);
        btnLocalizar.setFocusPainted(false);
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 160, 32));

        btnListado.setBackground(new java.awt.Color(44, 50, 62));
        btnListado.setForeground(new java.awt.Color(255, 255, 255));
        btnListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/archivo.png"))); // NOI18N
        btnListado.setText("Generar listado");
        btnListado.setBorderPainted(false);
        btnListado.setFocusPainted(false);
        btnListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoActionPerformed(evt);
            }
        });
        jPanel3.add(btnListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 52, 130, 32));

        tablaInventario.setBackground(new java.awt.Color(36, 41, 51));
        tablaInventario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tablaInventario.setForeground(new java.awt.Color(220, 225, 235));
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Estado", "Cantidad", "Ubicación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaInventario.setEnabled(false);
        tablaInventario.setGridColor(new java.awt.Color(60, 68, 85));
        tablaInventario.setRowHeight(30);
        tablaInventario.setSelectionBackground(new java.awt.Color(12, 60, 120));
        tablaInventario.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaInventario.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tablaInventario);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 760, 480));

        lblError.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblError.setForeground(new java.awt.Color(180, 50, 50));
        jPanel3.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 420, 20));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void cargarTabla() {
            
        String[] columnas = {"ID", "Nombre", "Categoría", "Estado", "Cantidad", "Ubicacion"};

        DefaultTableModel tabla = new DefaultTableModel(columnas, 0);// 0 filas iniciales

        String sql = "SELECT m.id_material, m.nombre, c.nombre as categoria, " +
                         "e.nombre as estado, m.cantidad, u.espacio " +
                         "FROM material m " +
                         "JOIN categorias c ON c.id_categoria = m.id_categoria " +
                         "JOIN estado e ON e.id_estado = m.id_estado "  +
                         "JOIN ubicaciones u ON u.codigo_armario = m.id_ubicacion";

            try (PreparedStatement ps = AccesoBaseDatos.getInstance().getConn().prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {
                    tabla.addRow(new Object[]{
                        rs.getInt("id_material"),
                        rs.getString("nombre"),
                        rs.getString("categoria"),
                        rs.getString("estado"),
                        rs.getInt("cantidad"),
                        rs.getString("espacio")
                    });
                }

            } catch (SQLException e) {
                System.out.println("SQL ERROR -> " + e.getMessage());
            }

        tablaInventario.setModel(tabla);// muestra los datos que metes en 'tabla'
    }
    
    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        dispose();
        
        new LoginFrame().setVisible(true);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        
        String buscador = txtBuscar.getText().trim();
        
        if(buscador.equalsIgnoreCase("")) {
            cargarTabla();
            return;
            
        }
        
        String[] columnas = {"ID", "Nombre", "Categoría", "Estado", "Cantidad", "Ubicacion"};

        DefaultTableModel tabla = new DefaultTableModel(columnas, 0);

        String sql = "SELECT m.id_material, m.nombre, c.nombre as categoria, " +
                         "e.nombre as estado, m.cantidad, u.espacio " +
                         "FROM material m " +
                         "JOIN categorias c ON c.id_categoria = m.id_categoria " +
                         "JOIN estado e ON e.id_estado = m.id_estado "  +
                         "JOIN ubicaciones u ON u.codigo_armario = m.id_ubicacion WHERE m.nombre=?";

            try (PreparedStatement ps = AccesoBaseDatos.getInstance().getConn().prepareStatement(sql)){
            
            ps.setString(1, buscador);
            
            try(ResultSet rs = ps.executeQuery()) {
                
                while (rs.next()) {
                    tabla.addRow(new Object[]{
                        rs.getInt("id_material"),
                        rs.getString("nombre"),
                        rs.getString("categoria"),
                        rs.getString("estado"),
                        rs.getInt("cantidad"),
                        rs.getString("espacio")
                    });
                }
                
            }
                       
        } catch (SQLException ex) {
            System.out.println("SQL ERROR -> " + ex.getMessage());
        }

        tablaInventario.setModel(tabla);
        
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        
        lblError.setText("");
        
        try {
            Desktop.getDesktop().browse( new URI("http://10.0.10.39"));
        } catch (URISyntaxException ex) {
            lblError.setText("No se ha podido abrir la web");
        } catch (IOException ex) {
            lblError.setText("No se ha podido abrir la web");
        }
        
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        lblError.setText("");
        String estado = cmbEstado.getSelectedItem().toString();
        
        if(estado.equalsIgnoreCase("Todos los estados")){
            cargarTabla();
            return;
        }
        
        String[] columnas = {"ID", "Nombre", "Categoría", "Estado", "Cantidad", "Ubicacion"};

        DefaultTableModel tabla = new DefaultTableModel(columnas, 0);// 0 filas iniciales

        String sql = "SELECT m.id_material, m.nombre, c.nombre as categoria, " +
                         "e.nombre as estado, m.cantidad, u.espacio " +
                         "FROM material m " +
                         "JOIN categorias c ON c.id_categoria = m.id_categoria " +
                         "JOIN estado e ON e.id_estado = m.id_estado "  +
                         "JOIN ubicaciones u ON u.codigo_armario = m.id_ubicacion WHERE e.nombre=?";

            try (PreparedStatement ps = AccesoBaseDatos.getInstance().getConn().prepareStatement(sql)){
            
            ps.setString(1, estado);
            
            try(ResultSet rs = ps.executeQuery()) {
                
                while (rs.next()) {
                    tabla.addRow(new Object[]{
                        rs.getInt("id_material"),
                        rs.getString("nombre"),
                        rs.getString("categoria"),
                        rs.getString("estado"),
                        rs.getInt("cantidad"),
                        rs.getString("espacio")
                    });
                }
                
            }
                       
        } catch (SQLException ex) {
            System.out.println("SQL ERROR -> " + ex.getMessage());
        }

        tablaInventario.setModel(tabla);// muestra los datos que metes en 'tabla'
        
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        
        lblError.setText("");
        
        String categoria = cmbCategoria.getSelectedItem().toString();
        
        if(categoria.equalsIgnoreCase("Todas las categorias")) {
            cargarTabla();
            return;
            
        }
        
        String[] columnas = {"ID", "Nombre", "Categoría", "Estado", "Cantidad", "Ubicacion"};

        DefaultTableModel tabla = new DefaultTableModel(columnas, 0);

        String sql = "SELECT m.id_material, m.nombre, c.nombre as categoria, " +
                         "e.nombre as estado, m.cantidad, u.espacio " +
                         "FROM material m " +
                         "JOIN categorias c ON c.id_categoria = m.id_categoria " +
                         "JOIN estado e ON e.id_estado = m.id_estado "  +
                         "JOIN ubicaciones u ON u.codigo_armario = m.id_ubicacion WHERE c.nombre=?";

            try (PreparedStatement ps = AccesoBaseDatos.getInstance().getConn().prepareStatement(sql)){
            
            ps.setString(1, categoria);
            
            try(ResultSet rs = ps.executeQuery()) {
                
                while (rs.next()) {
                    tabla.addRow(new Object[]{
                        rs.getInt("id_material"),
                        rs.getString("nombre"),
                        rs.getString("categoria"),
                        rs.getString("estado"),
                        rs.getInt("cantidad"),
                        rs.getString("espacio")
                    });
                }
                
            }
                       
        } catch (SQLException ex) {
            System.out.println("SQL ERROR -> " + ex.getMessage());
        }

        tablaInventario.setModel(tabla);
        
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoActionPerformed
        
        try {
                        
            GestorCSV.exportar("material_profe.csv");
            
            JOptionPane.showMessageDialog(this, "Lista exportada correctamente");

        } catch (Exception e) {
            lblError.setText("Ocurrio un error al exportar el fichero");
        }
        
    }//GEN-LAST:event_btnListadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String nombre = null;
                new ProfesorFrame(nombre).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnListado;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblError;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JLabel txtProfesorNombre;
    // End of variables declaration//GEN-END:variables
}
